version: '3.8'
services:
  dhcp:
    build: ./dhcp
    container_name: dhcp
    restart: always
    environment:
      - INTERFACES=eth0
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./dhcp/dhcpd.leases:/var/lib/dhcp/dhcpd.leases
    networks:
      - dhcp_network
    ports:
      - "67:67/udp"
  firewall:
    build: ./firewall
    container_name: firewall
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    environment:
      - HOST_NETWORK_INTERFACE=HOST_NETWORK_INTERFACE
networks:
  dhcp_network:
    external: true